"""Focused, proof-gated Genesis kernel synthesis laboratory."""

from .benchmark import benchmark_candidate, decide_candidate
from .cases import generate_correctness_cases, reference_quantized_state_update
from .demo import run_kernel_lab_demo
from .evidence import BottleneckEvidenceError, validate_bottleneck_evidence
from .executor import execute_correctness
from .generator import (
    generate_candidates,
    hybrid_quantized_state_schema,
    validate_generated_source,
)
from .models import (
    KERNEL_LAB_SCHEMA_VERSION,
    AcceptanceStatus,
    AdapterStatus,
    AliasingConstraint,
    ArchitectureConstraint,
    BenchmarkRegimeEvidence,
    BenchmarkSample,
    BottleneckEvidence,
    CandidateDecision,
    CaseResult,
    CorrectnessEvidence,
    CorrectnessMismatch,
    EvidenceSource,
    KernelBackend,
    KernelBenchmarkConfig,
    KernelBenchmarkReport,
    KernelCandidate,
    KernelCase,
    KernelLabReport,
    KernelParameters,
    LabStatus,
    NumericalContract,
    OperatorSchema,
    RawBottleneckRecord,
    ShapeDimension,
    TensorConstraint,
    TritonAdapterReport,
)
from .triton import triton_adapter_status

__all__ = [
    "KERNEL_LAB_SCHEMA_VERSION",
    "AcceptanceStatus",
    "AdapterStatus",
    "AliasingConstraint",
    "ArchitectureConstraint",
    "BenchmarkRegimeEvidence",
    "BenchmarkSample",
    "BottleneckEvidence",
    "BottleneckEvidenceError",
    "CandidateDecision",
    "CaseResult",
    "CorrectnessEvidence",
    "CorrectnessMismatch",
    "EvidenceSource",
    "KernelBackend",
    "KernelBenchmarkConfig",
    "KernelBenchmarkReport",
    "KernelCandidate",
    "KernelCase",
    "KernelLabReport",
    "KernelParameters",
    "LabStatus",
    "NumericalContract",
    "OperatorSchema",
    "RawBottleneckRecord",
    "ShapeDimension",
    "TensorConstraint",
    "TritonAdapterReport",
    "benchmark_candidate",
    "decide_candidate",
    "execute_correctness",
    "generate_candidates",
    "generate_correctness_cases",
    "hybrid_quantized_state_schema",
    "reference_quantized_state_update",
    "run_kernel_lab_demo",
    "triton_adapter_status",
    "validate_bottleneck_evidence",
    "validate_generated_source",
]
