"""Generate content-identified model-specific conservative runtime bundles."""

from __future__ import annotations

import hashlib
import json
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

from sloforge.genesis.frontend.models import DiagnosticSeverity, InspectionResult
from sloforge.genesis.frontend.package import load_reference_package
from sloforge.genesis.policy_dsl import BytecodeProgram, load_bytecode_document
from sloforge.util import sha256_file

from .adapter import ReferenceRuntimeAdapter
from .core import BaselineStreamingRuntime
from .models import RuntimeLimits, StateAllocatorConfig, StateAllocatorLayout

GENERATED_RUNTIME_SCHEMA_VERSION = "1.0.0"


@dataclass(frozen=True)
class GeneratedRuntimeBundle:
    output_directory: Path
    runtime_id: str
    package_hash: str
    artifact_hashes: tuple[tuple[str, str], ...]


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            return
        raise FileExistsError(f"refusing to overwrite generated runtime artifact: {path}")
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temporary = Path(handle.name)
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        temporary = None
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def _canonical(value: object) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False) + "\n"


_RUNTIME_SOURCE = '''"""Generated by SLOForge Genesis; model-specific inputs are in runtime_config.json."""

import argparse
import json
import os
import sys
from pathlib import Path
from threading import Lock, Thread

from sloforge.genesis.runtime import GeneratedRuntimeApplication, load_generated_runtime

MAXIMUM_REQUEST_BYTES = 65536
MAXIMUM_CONCURRENT_REQUESTS = 36
MAXIMUM_TIMEOUT_SECONDS = 30.0
_write_lock = Lock()


def application(*, seed: int) -> GeneratedRuntimeApplication:
    runtime = load_generated_runtime(Path(__file__).with_name("runtime_config.json"), seed=seed)
    return GeneratedRuntimeApplication(runtime)


def _write(value: object) -> None:
    with _write_lock:
        sys.stdout.write(json.dumps(value, sort_keys=True, separators=(",", ":")) + "\\n")
        sys.stdout.flush()


def _stream(handle, timeout_seconds: float, active: dict, active_lock: Lock) -> None:
    try:
        for event in handle.events(timeout_seconds):
            _write(
                {
                    "kind": event.kind.value,
                    "message": event.message,
                    "request_id": event.request_id,
                    "sequence": event.sequence,
                    "text": event.text,
                    "token_id": event.token_id,
                }
            )
    except TimeoutError as error:
        handle.cancel()
        _write(
            {
                "kind": "error",
                "message": f"TimeoutError: {error}",
                "request_id": handle.request_id,
            }
        )
    finally:
        with active_lock:
            active.pop(handle.request_id, None)


def main() -> int:
    if os.environ.get("SLOFORGE_GENESIS_SANDBOX_LAUNCH") != "sandbox-executor-v1":
        sys.stderr.write(
            "generated runtimes must be launched by the trusted Genesis sandbox executor\\n"
        )
        return 78
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed", type=int, required=True)
    args = parser.parse_args()
    app = application(seed=args.seed)
    active = {}
    active_lock = Lock()
    stream_threads = []
    app.start()
    try:
        while True:
            encoded = sys.stdin.buffer.readline(MAXIMUM_REQUEST_BYTES + 1)
            if not encoded:
                return 0
            if len(encoded) > MAXIMUM_REQUEST_BYTES:
                _write({"kind": "error", "message": "request exceeds bounded input size"})
                return 2
            try:
                request = json.loads(encoded)
                if not isinstance(request, dict):
                    raise TypeError("request must be a JSON object")
                operation = request.get("operation", "submit")
                if operation in {"health", "metrics"}:
                    path = "/healthz" if operation == "health" else "/metrics"
                    status, body = app.handle_get(path)
                    _write({"body": body, "kind": "control", "status": status})
                    continue
                if operation == "cancel":
                    request_id = request["request_id"]
                    with active_lock:
                        handle = active.get(request_id)
                    if handle is None:
                        raise ValueError("request is not active")
                    if not handle.cancel():
                        raise ValueError("request has already reached a terminal state")
                    _write({"kind": "control", "operation": "cancel", "request_id": request_id})
                    continue
                if operation == "shutdown":
                    _write({"kind": "control", "operation": "shutdown"})
                    return 0
                if operation != "submit":
                    raise ValueError("unsupported operation")
                timeout_seconds = float(request["timeout_seconds"])
                if not 0.0 < timeout_seconds <= MAXIMUM_TIMEOUT_SECONDS:
                    raise ValueError("timeout_seconds is outside the bounded subprocess domain")
                with active_lock:
                    if len(active) >= MAXIMUM_CONCURRENT_REQUESTS:
                        raise ValueError("bounded concurrent request registry is full")
                handle = app.runtime.submit_text(
                    request_id=request["request_id"],
                    text=request["text"],
                    maximum_new_tokens=request["maximum_new_tokens"],
                    seed=request["seed"],
                    timeout_seconds=timeout_seconds,
                    batching_eligible=request.get("batching_eligible", True),
                )
                with active_lock:
                    active[handle.request_id] = handle
                thread = Thread(
                    target=_stream,
                    args=(handle, timeout_seconds, active, active_lock),
                    name=f"genesis-stream-{handle.request_id}",
                    daemon=False,
                )
                thread.start()
                stream_threads = [item for item in stream_threads if item.is_alive()]
                stream_threads.append(thread)
            except (KeyError, TypeError, ValueError, TimeoutError) as error:
                _write({"kind": "error", "message": f"{type(error).__name__}: {error}"})
    finally:
        with active_lock:
            handles = tuple(active.values())
        for handle in handles:
            handle.cancel()
        app.shutdown()
        for thread in stream_threads:
            thread.join(MAXIMUM_TIMEOUT_SECONDS)


if __name__ == "__main__":
    raise SystemExit(main())
'''


_HARNESS_SOURCE = '''"""Differential fixture harness for this generated reference runtime."""

import argparse
import json
from pathlib import Path

from runtime import application


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--samples", type=Path, required=True)
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--timeout-seconds", type=float, default=5.0)
    args = parser.parse_args()
    app = application(seed=args.seed)
    failures = []
    cases = []
    try:
        app.start()
        for line_number, line in enumerate(args.samples.read_text(encoding="utf-8").splitlines(), 1):
            if not line.strip():
                continue
            sample = json.loads(line)
            handle = app.runtime.submit_text(
                request_id=f"fixture-{line_number}",
                text=sample["text"],
                maximum_new_tokens=sample["maximum_new_tokens"],
                seed=sample["seed"],
                timeout_seconds=args.timeout_seconds,
            )
            observed = [event.token_id for event in handle.events(args.timeout_seconds) if event.token_id is not None]
            expected = sample.get("expected_tokens")
            exact = expected is None or observed == expected
            cases.append(
                {
                    "line": line_number,
                    "request_seed": sample["seed"],
                    "expected": expected,
                    "observed": observed,
                    "exact_match": exact,
                }
            )
            if expected is not None and observed != expected:
                failures.append({"line": line_number, "expected": expected, "observed": observed})
    finally:
        app.shutdown()
    print(json.dumps({"cases": cases, "failures": failures, "passed": bool(cases) and not failures}, sort_keys=True))
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def generate_baseline_runtime(
    package_path: Path,
    inspection: InspectionResult,
    output_directory: Path,
    *,
    seed: int,
    genome_hash: str | None = None,
) -> GeneratedRuntimeBundle:
    """Generate a runtime bundle only from a matching static inspection."""

    package = load_reference_package(package_path)
    if package.package_hash != inspection.package_hash:
        raise ValueError("inspection no longer matches the reference package content")
    unsupported = [
        diagnostic
        for diagnostic in inspection.diagnostics
        if diagnostic.severity == DiagnosticSeverity.UNSUPPORTED
    ]
    if unsupported:
        messages = "; ".join(item.message for item in unsupported)
        raise ValueError(f"cannot synthesize runtime with unsupported semantics: {messages}")
    runtime_id = hashlib.sha256(
        f"{package.package_hash}\0{inspection.manifest_hash}\0{seed}".encode()
    ).hexdigest()
    dtype_bytes = {
        "bool": 1,
        "float64": 8,
        "float32": 4,
        "bfloat16": 2,
        "float16": 2,
        "int64": 8,
        "int32": 4,
        "int16": 2,
        "int8": 1,
        "uint8": 1,
    }
    state_bytes_per_request = 0
    for field in package.manifest.state_contract.fields:
        elements = 1
        for dimension in field.shape:
            elements *= dimension.maximum
        try:
            state_bytes_per_request += elements * dtype_bytes[field.dtype]
        except KeyError as error:
            raise ValueError(
                f"unsupported state dtype for bounded allocation: {field.dtype}"
            ) from error
    state_bytes_per_request = max(1, state_bytes_per_request)
    config = {
        "schema_version": GENERATED_RUNTIME_SCHEMA_VERSION,
        "runtime_id": runtime_id,
        "reference_package_root": str(package.root),
        "package_hash": package.package_hash,
        "inspection_hash": hashlib.sha256(
            json.dumps(
                inspection.model_dump(mode="json"),
                sort_keys=True,
                separators=(",", ":"),
                allow_nan=False,
            ).encode("utf-8")
        ).hexdigest(),
        "genome_hash": genome_hash,
        "generation_seed": seed,
        "policy_bytecode_path": None,
        "policy_bytecode_sha256": None,
        "state_allocator": {
            "layout": "contiguous",
            "page_bytes": 64,
            "maximum_bytes_per_request": state_bytes_per_request,
            "maximum_total_bytes": 32 * state_bytes_per_request,
        },
        "limits": {
            "maximum_queue_depth": 32,
            "maximum_batch_size": 4,
            "maximum_prompt_tokens": package.manifest.supported_input_domain.maximum_prompt_tokens,
            "maximum_generated_tokens": package.manifest.supported_input_domain.maximum_generated_tokens,
            "maximum_output_events_per_request": (
                package.manifest.supported_input_domain.maximum_generated_tokens + 1
            ),
            "batch_wait_seconds": 0.002,
            "queue_operation_timeout_seconds": 0.5,
            "worker_poll_seconds": 0.05,
            "shutdown_timeout_seconds": 5.0,
        },
    }
    deployment = {
        "schema_version": "1.0.0",
        "runtime_id": runtime_id,
        "offline": True,
        "trusted_launcher": "sloforge.genesis.sandbox.execute_sandboxed",
        "sandbox_argv": ["python", "runtime.py", "--seed", "<required>"],
        "direct_launch_supported": False,
        "health_endpoint": "/healthz",
        "metrics_endpoint": "/metrics",
        "network_enabled": False,
        "read_only_inputs": [str(package.root)],
        "writable_artifact_directory": "/artifacts",
        "queue_capacity": 32,
        "request_timeout_required": True,
    }
    output_directory.mkdir(parents=True, exist_ok=True)
    _atomic_write(output_directory / "runtime.py", _RUNTIME_SOURCE)
    _atomic_write(output_directory / "correctness_harness.py", _HARNESS_SOURCE)
    _atomic_write(output_directory / "runtime_config.json", _canonical(config))
    _atomic_write(output_directory / "deployment_manifest.json", _canonical(deployment))
    artifacts = tuple(
        (name, sha256_file(output_directory / name))
        for name in (
            "correctness_harness.py",
            "deployment_manifest.json",
            "runtime.py",
            "runtime_config.json",
        )
    )
    _atomic_write(
        output_directory / "artifact_manifest.json",
        _canonical(
            {
                "schema_version": "1.0.0",
                "runtime_id": runtime_id,
                "package_hash": package.package_hash,
                "artifacts": artifacts,
            }
        ),
    )
    return GeneratedRuntimeBundle(
        output_directory=output_directory,
        runtime_id=runtime_id,
        package_hash=package.package_hash,
        artifact_hashes=artifacts,
    )


def _load_config(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("generated runtime config must be an object")
    config = cast(dict[str, Any], value)
    required = {
        "schema_version",
        "runtime_id",
        "reference_package_root",
        "package_hash",
        "inspection_hash",
        "genome_hash",
        "generation_seed",
        "limits",
    }
    optional = {"policy_bytecode_path", "policy_bytecode_sha256", "state_allocator"}
    if not required.issubset(config) or not set(config).issubset(required | optional):
        raise ValueError("generated runtime config contains missing or unknown fields")
    if config["schema_version"] != GENERATED_RUNTIME_SCHEMA_VERSION:
        raise ValueError("unsupported generated runtime schema version")
    return config


def _load_policy_bytecode(config_path: Path, config: dict[str, Any]) -> BytecodeProgram | None:
    value = config.get("policy_bytecode_path")
    digest = config.get("policy_bytecode_sha256")
    if value is None and digest is None:
        return None
    if not isinstance(value, str) or not value or not isinstance(digest, str):
        raise ValueError("runtime policy path and digest must be declared together")
    path = Path(value)
    if not path.is_absolute():
        path = config_path.parent / path
    payload = path.read_bytes()
    if hashlib.sha256(payload).hexdigest() != digest:
        raise ValueError("runtime policy bytecode digest mismatch")
    return load_bytecode_document(payload)


def _load_state_allocator(config: dict[str, Any]) -> StateAllocatorConfig:
    value = config.get("state_allocator")
    if value is None:
        return StateAllocatorConfig()
    if not isinstance(value, dict) or set(value) != {
        "layout",
        "page_bytes",
        "maximum_bytes_per_request",
        "maximum_total_bytes",
    }:
        raise ValueError("generated runtime state allocator is missing bounded typed fields")
    try:
        layout = StateAllocatorLayout(value["layout"])
    except (TypeError, ValueError) as error:
        raise ValueError("generated runtime state allocator layout is unsupported") from error
    return StateAllocatorConfig(
        layout=layout,
        page_bytes=value["page_bytes"],
        maximum_bytes_per_request=value["maximum_bytes_per_request"],
        maximum_total_bytes=value["maximum_total_bytes"],
    )


def load_generated_runtime(
    config_path: Path,
    *,
    seed: int,
    allow_untrusted_in_process: bool = False,
) -> BaselineStreamingRuntime:
    """Load a generated runtime only inside the sandbox or explicit test-only opt-in."""

    if (
        os.environ.get("SLOFORGE_GENESIS_SANDBOX_LAUNCH") != "sandbox-executor-v1"
        and not allow_untrusted_in_process
    ):
        raise PermissionError(
            "generated runtimes may be imported only by the Genesis sandbox executor; "
            "allow_untrusted_in_process is reserved for explicit trusted tests"
        )

    config = _load_config(config_path)
    package_root = Path(str(config["reference_package_root"]))
    if not package_root.is_absolute():
        package_root = config_path.parent / package_root
    package = load_reference_package(package_root)
    if package.package_hash != config["package_hash"]:
        raise ValueError("reference package changed after runtime generation")
    limits_value = config["limits"]
    if not isinstance(limits_value, dict):
        raise TypeError("generated runtime limits must be an object")
    limits = RuntimeLimits(**cast(dict[str, Any], limits_value))
    adapter = ReferenceRuntimeAdapter(
        reference_path=package.resolve(package.manifest.reference_module),
        tokenizer_path=package.resolve(package.manifest.tokenizer_module),
        entry_points=package.manifest.entry_points,
        identity=f"genesis_{config['runtime_id']}",
        seed=seed,
    )
    return BaselineStreamingRuntime(
        adapter,
        limits=limits,
        runtime_seed=seed,
        policy=_load_policy_bytecode(config_path, config),
        state_allocator=_load_state_allocator(config),
    )


class GeneratedRuntimeApplication:
    """In-process endpoint surface; network serving remains sandbox-controlled."""

    def __init__(self, runtime: BaselineStreamingRuntime) -> None:
        self.runtime = runtime

    def start(self) -> None:
        self.runtime.start()

    def shutdown(self) -> None:
        self.runtime.shutdown()

    def handle_get(self, path: str) -> tuple[int, dict[str, object]]:
        if path == "/healthz":
            return 200, self.runtime.health()
        if path == "/metrics":
            metrics: dict[str, object] = {
                key: value for key, value in self.runtime.metrics().items()
            }
            return 200, metrics
        return 404, {"error": "not_found"}
