"""Proof-gated, restart-safe Genesis champion/challenger evolution."""

from .controller import (
    CapsuleValidator,
    EvolutionController,
    EvolutionError,
    GateEvidenceValidator,
    TransitionCompatibilityValidator,
    classify_trigger,
)
from .evidence import collect_local_gate_evidence
from .fixture import run_local_evolution_fixture
from .models import (
    EVOLUTION_SCHEMA_VERSION,
    PERSISTENCE_SCHEMA_VERSION,
    CapsuleReference,
    ChallengerRecord,
    ChallengerSpec,
    ChallengerStatus,
    EvolutionAuditRecord,
    EvolutionConfig,
    EvolutionPhase,
    EvolutionSnapshot,
    EvolutionTrigger,
    ExecutionTarget,
    GateObservation,
    GateStage,
    IsolationContract,
    IsolationMode,
    PersistedEvolutionState,
    ProcessedEventRecord,
    StreamLease,
    TransitionCategory,
    TriggerObservation,
)
from .store import EvolutionPersistenceError, EvolutionStore
from .transition import TransitionCompatibility, validate_transition_compatibility

__all__ = [
    "EVOLUTION_SCHEMA_VERSION",
    "PERSISTENCE_SCHEMA_VERSION",
    "CapsuleReference",
    "CapsuleValidator",
    "ChallengerRecord",
    "ChallengerSpec",
    "ChallengerStatus",
    "EvolutionAuditRecord",
    "EvolutionConfig",
    "EvolutionController",
    "EvolutionError",
    "EvolutionPersistenceError",
    "EvolutionPhase",
    "EvolutionSnapshot",
    "EvolutionStore",
    "EvolutionTrigger",
    "ExecutionTarget",
    "GateEvidenceValidator",
    "GateObservation",
    "GateStage",
    "IsolationContract",
    "IsolationMode",
    "PersistedEvolutionState",
    "ProcessedEventRecord",
    "StreamLease",
    "TransitionCategory",
    "TransitionCompatibility",
    "TransitionCompatibilityValidator",
    "TriggerObservation",
    "classify_trigger",
    "collect_local_gate_evidence",
    "run_local_evolution_fixture",
    "validate_transition_compatibility",
]
