"""Generated by SLOForge Genesis; model-specific inputs are in runtime_config.json."""

import argparse
import json
import os
import sys
from pathlib import Path
from threading import Lock, Thread

from sloforge.genesis.runtime import GeneratedRuntimeApplication, load_generated_runtime

MAXIMUM_REQUEST_BYTES = 65536
MAXIMUM_CONCURRENT_REQUESTS = 36
MAXIMUM_TIMEOUT_SECONDS = 30.0
_write_lock = Lock()


def application(*, seed: int) -> GeneratedRuntimeApplication:
    runtime = load_generated_runtime(Path(__file__).with_name("runtime_config.json"), seed=seed)
    return GeneratedRuntimeApplication(runtime)


def _write(value: object) -> None:
    with _write_lock:
        sys.stdout.write(json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n")
        sys.stdout.flush()


def _stream(handle, timeout_seconds: float, active: dict, active_lock: Lock) -> None:
    try:
        for event in handle.events(timeout_seconds):
            _write(
                {
                    "kind": event.kind.value,
                    "message": event.message,
                    "request_id": event.request_id,
                    "sequence": event.sequence,
                    "text": event.text,
                    "token_id": event.token_id,
                }
            )
    except TimeoutError as error:
        handle.cancel()
        _write(
            {
                "kind": "error",
                "message": f"TimeoutError: {error}",
                "request_id": handle.request_id,
            }
        )
    finally:
        with active_lock:
            active.pop(handle.request_id, None)


def main() -> int:
    if os.environ.get("SLOFORGE_GENESIS_SANDBOX_LAUNCH") != "sandbox-executor-v1":
        sys.stderr.write(
            "generated runtimes must be launched by the trusted Genesis sandbox executor\n"
        )
        return 78
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed", type=int, required=True)
    args = parser.parse_args()
    app = application(seed=args.seed)
    active = {}
    active_lock = Lock()
    stream_threads = []
    app.start()
    try:
        while True:
            encoded = sys.stdin.buffer.readline(MAXIMUM_REQUEST_BYTES + 1)
            if not encoded:
                return 0
            if len(encoded) > MAXIMUM_REQUEST_BYTES:
                _write({"kind": "error", "message": "request exceeds bounded input size"})
                return 2
            try:
                request = json.loads(encoded)
                if not isinstance(request, dict):
                    raise TypeError("request must be a JSON object")
                operation = request.get("operation", "submit")
                if operation in {"health", "metrics"}:
                    path = "/healthz" if operation == "health" else "/metrics"
                    status, body = app.handle_get(path)
                    _write({"body": body, "kind": "control", "status": status})
                    continue
                if operation == "cancel":
                    request_id = request["request_id"]
                    with active_lock:
                        handle = active.get(request_id)
                    if handle is None:
                        raise ValueError("request is not active")
                    if not handle.cancel():
                        raise ValueError("request has already reached a terminal state")
                    _write({"kind": "control", "operation": "cancel", "request_id": request_id})
                    continue
                if operation == "shutdown":
                    _write({"kind": "control", "operation": "shutdown"})
                    return 0
                if operation != "submit":
                    raise ValueError("unsupported operation")
                timeout_seconds = float(request["timeout_seconds"])
                if not 0.0 < timeout_seconds <= MAXIMUM_TIMEOUT_SECONDS:
                    raise ValueError("timeout_seconds is outside the bounded subprocess domain")
                with active_lock:
                    if len(active) >= MAXIMUM_CONCURRENT_REQUESTS:
                        raise ValueError("bounded concurrent request registry is full")
                handle = app.runtime.submit_text(
                    request_id=request["request_id"],
                    text=request["text"],
                    maximum_new_tokens=request["maximum_new_tokens"],
                    seed=request["seed"],
                    timeout_seconds=timeout_seconds,
                    batching_eligible=request.get("batching_eligible", True),
                )
                with active_lock:
                    active[handle.request_id] = handle
                thread = Thread(
                    target=_stream,
                    args=(handle, timeout_seconds, active, active_lock),
                    name=f"genesis-stream-{handle.request_id}",
                    daemon=False,
                )
                thread.start()
                stream_threads = [item for item in stream_threads if item.is_alive()]
                stream_threads.append(thread)
            except (KeyError, TypeError, ValueError, TimeoutError) as error:
                _write({"kind": "error", "message": f"{type(error).__name__}: {error}"})
    finally:
        with active_lock:
            handles = tuple(active.values())
        for handle in handles:
            handle.cancel()
        app.shutdown()
        for thread in stream_threads:
            thread.join(MAXIMUM_TIMEOUT_SECONDS)


if __name__ == "__main__":
    raise SystemExit(main())
