"""Generated by SLOForge from plan opt-6bc8aed6c3b3caee; importing this module creates no resources."""
import modal

MODEL_ID = 'sloforge/mock-qwen3-0.6b-shape'
MODEL_REVISION = 'cpu-demo-v1'
EXPECTED_GPU_COUNT = 0
image = modal.Image.debian_slim(python_version="3.12").uv_pip_install(
    'fastapi[standard]==0.116.1', 'httpx==0.28.1'
)
app = modal.App('sloforge-opt-6bc8aed6c3b3caee', image=image)

@app.cls(
    gpu=None,
    cpu=6.0,
    memory=24576,
    min_containers=1,
    max_containers=4,
    scaledown_window=120,
    region=None,
    enable_memory_snapshot=False,
    timeout=150,
)
@modal.concurrent(max_inputs=6, target_inputs=6)
class Inference:
    @modal.enter(snap=False)
    def load(self):
        self.engine = None

    @modal.fastapi_endpoint(method="POST", docs=True)
    def generate(self, request: dict):
        prompt = str(request.get("prompt", ""))
        max_tokens = max(1, min(int(request.get("max_tokens", 64)), 32768))
        if not prompt:
            raise ValueError("prompt must be non-empty")
        text = f"explicit-mock:{prompt[:64]}"
        return {"model": MODEL_ID, "choices": [{"text": text}]}
