"""Deterministic, SLO-hard, learning-aware Helix resource scheduling."""

from .adapters import FabricCapacityMapping, FabricResourceBinding, capacity_from_fabric
from .compiler import SchedulingInfeasibleError, compile_resource_plan
from .evaluation import evaluate_learning_value
from .io import MAX_SCHEDULER_SCENARIO_BYTES, load_scheduler_request
from .models import (
    AuditDecision,
    BudgetAccounting,
    ClassResourceVectors,
    DecisionKind,
    EffectClass,
    EvidenceRef,
    FaultKind,
    LearningValueComparison,
    LearningValueEvaluation,
    PreemptionRecord,
    PreservationAccounting,
    PreservationMode,
    PreservationOption,
    PrivacyClass,
    RawLearningValueSample,
    ResourcePrices,
    ResourceVector,
    SchedulerConstraints,
    SchedulerFault,
    SchedulerPlan,
    SchedulerPolicy,
    SchedulerRequest,
    ServingDemandSample,
    ServingSLO,
    TickAllocation,
    ValuePrediction,
    WorkClass,
    WorkOutcome,
    WorkStatus,
    WorkUnit,
    restart_only,
)

__all__ = [
    "MAX_SCHEDULER_SCENARIO_BYTES",
    "AuditDecision",
    "BudgetAccounting",
    "ClassResourceVectors",
    "DecisionKind",
    "EffectClass",
    "EvidenceRef",
    "FabricCapacityMapping",
    "FabricResourceBinding",
    "FaultKind",
    "LearningValueComparison",
    "LearningValueEvaluation",
    "PreemptionRecord",
    "PreservationAccounting",
    "PreservationMode",
    "PreservationOption",
    "PrivacyClass",
    "RawLearningValueSample",
    "ResourcePrices",
    "ResourceVector",
    "SchedulerConstraints",
    "SchedulerFault",
    "SchedulerPlan",
    "SchedulerPolicy",
    "SchedulerRequest",
    "SchedulingInfeasibleError",
    "ServingDemandSample",
    "ServingSLO",
    "TickAllocation",
    "ValuePrediction",
    "WorkClass",
    "WorkOutcome",
    "WorkStatus",
    "WorkUnit",
    "capacity_from_fabric",
    "compile_resource_plan",
    "evaluate_learning_value",
    "load_scheduler_request",
    "restart_only",
]
