"""Typed Continuum state-transformation compiler and trusted CPU converters."""

from .adapter_bridge import (
    LiveConversionEvidence,
    captured_attention_state,
    direct_convert_capture,
)
from .compiler import (
    ConversionCompilationError,
    ConvertedChunk,
    canonical_convert,
    compile_conversion,
    direct_convert,
    stream_direct_conversion,
)
from .ir import (
    ChunkAssignment,
    ChunkSchedule,
    MemoryPlan,
    OperationCode,
    OwnershipBehavior,
    ParameterValue,
    ShapeTransformation,
    StateTransformationIR,
    TargetDevice,
    TensorContract,
    TransformationDAG,
    TransformationOperation,
)
from .layouts import (
    KVLayout,
    KVLayoutKind,
    KVShard,
    LayoutValidationError,
    PhysicalKVState,
    StateIntegrityError,
    allocate_state,
    decode_logical,
    encode_logical,
    make_random_state,
)
from .pytorch_backend import PyTorchConversionEvidence, pytorch_convert
from .verification import (
    ConversionBackend,
    ConversionMeasurement,
    ConversionSelection,
    ConversionVerificationEvidence,
    QualityBoundedConversionEvidence,
    measure_and_select_converter,
    quality_bounded_convert,
    verify_direct_against_canonical,
)

__all__ = [
    "ChunkAssignment",
    "ChunkSchedule",
    "ConversionBackend",
    "ConversionCompilationError",
    "ConversionMeasurement",
    "ConversionSelection",
    "ConversionVerificationEvidence",
    "ConvertedChunk",
    "KVLayout",
    "KVLayoutKind",
    "KVShard",
    "LayoutValidationError",
    "LiveConversionEvidence",
    "MemoryPlan",
    "OperationCode",
    "OwnershipBehavior",
    "ParameterValue",
    "PhysicalKVState",
    "PyTorchConversionEvidence",
    "QualityBoundedConversionEvidence",
    "ShapeTransformation",
    "StateIntegrityError",
    "StateTransformationIR",
    "TargetDevice",
    "TensorContract",
    "TransformationDAG",
    "TransformationOperation",
    "allocate_state",
    "canonical_convert",
    "captured_attention_state",
    "compile_conversion",
    "decode_logical",
    "direct_convert",
    "direct_convert_capture",
    "encode_logical",
    "make_random_state",
    "measure_and_select_converter",
    "pytorch_convert",
    "quality_bounded_convert",
    "stream_direct_conversion",
    "verify_direct_against_canonical",
]
