export const validArtifact = {
  chaos: {
    confusion_matrix: { decode_dominance: { decode_dominance: 1 } },
    diagnosis_accuracy: 1,
    executed_at: "2026-01-01T00:00:01Z",
    executions: [
      {
        applied: true,
        counters_before: { decode_ms: 20 },
        counters_during: { decode_ms: 60 },
        diagnosis: {
          confidence: 0.9,
          correct: true,
          counterfactual_improvement_ms: 40,
          diagnosis_latency_ms: 8,
          evidence: ["decode contribution 60ms"],
          expected_label: "decode_dominance",
          fault_id: "slow-one",
          predicted_label: "decode_dominance",
        },
        event: {
          backend_id: "balanced",
          duration_ms: 500,
          fault_id: "slow-one",
          fault_type: "backend_slowdown",
          magnitude: 3,
          probability: 1,
          start_ms: 1000,
        },
      },
    ],
    false_positive_count: 0,
    false_positive_rate: 0,
    negative_window_count: 8,
    mean_diagnosis_latency_ms: 8,
    scenario_name: "explicit-test-fixture",
    schema_version: "sloforge.chaos-result/v1",
    seed: 7,
  },
  controller: {
    predictive: {
      action_count: 1,
      cold_start_exposure: 0,
      controller: "predictive",
      estimated_cost_usd: 0.002,
      recovery_windows: 0,
      replica_oscillations: 0,
      rollback_count: 0,
      slo_violations: 1,
    },
    predictive_decisions: [
      {
        actual_outcome_p95_ttft_ms: 170,
        canary: true,
        chosen: {
          action_type: "scale",
          admission_limit_rps: null,
          routing_policy: "slo_slack",
          target_concurrency: 8,
          target_replicas: 3,
          variant: "balanced",
        },
        controller_state_after: "canary",
        controller_state_before: "stable",
        decision_id: "predictive-00001",
        forecast: {
          arrival_rate_rps: 20,
          drift_score: 1.2,
          horizon_windows: 2,
          lower_rps: 15,
          upper_rps: 25,
        },
        generated_at: "2026-01-01T00:00:00Z",
        observed: {
          arrival_rate_rps: 18,
          backend_error_rate: 0,
          concurrency: 4,
          interactive_fraction: 0.75,
          long_context_fraction: 0.25,
          observed_p95_ttft_ms: 280,
          output_p95: 96,
          prompt_p95: 1024,
          replicas: 2,
          sample_count: 18,
          window_end_ms: 2000,
          window_index: 1,
          window_start_ms: 1000,
        },
        rollback_reason: null,
        rolled_back: false,
        safety_checks: ["change budget passed"],
      },
    ],
    reactive: {
      action_count: 1,
      cold_start_exposure: 1,
      controller: "reactive",
      estimated_cost_usd: 0.0015,
      recovery_windows: 2,
      replica_oscillations: 0,
      rollback_count: 0,
      slo_violations: 2,
    },
    reactive_decisions: [],
    schema_version: "sloforge.controller-result/v1",
    windows: [
      {
        arrival_rate_rps: 5,
        backend_error_rate: 0,
        concurrency: 4,
        interactive_fraction: 0.6,
        long_context_fraction: 0.4,
        observed_p95_ttft_ms: 90,
        output_p95: 72,
        prompt_p95: 700,
        replicas: 2,
        sample_count: 5,
        window_end_ms: 1000,
        window_index: 0,
        window_start_ms: 0,
      },
      {
        arrival_rate_rps: 18,
        backend_error_rate: 0,
        concurrency: 4,
        interactive_fraction: 0.75,
        long_context_fraction: 0.25,
        observed_p95_ttft_ms: 280,
        output_p95: 96,
        prompt_p95: 1024,
        replicas: 2,
        sample_count: 18,
        window_end_ms: 2000,
        window_index: 1,
        window_start_ms: 1000,
      },
    ],
  },
  metrics: {
    replay_slo_attainment: 0.5,
    selected_config_id: "cfg-selected",
  },
  pareto_frontier: [
    {
      configuration: {
        backend_candidate_id: "mock-balanced",
        chunked_prefill: true,
        concurrency: 4,
        config_id: "cfg-selected",
        max_batched_tokens: 512,
        replicas: 2,
        routing_policy: "slo_slack",
        warm_replicas: 1,
      },
      constraint_margins: { p95_ttft_ms: 50 },
      feasible: true,
      fidelity: "measured",
      measured: {
        cost_per_million_tokens: 1.5,
        p95_ttft_ms: 190,
        p99_itl_ms: 12,
      },
      predicted: {
        cost_per_million_tokens: 1.4,
        p95_ttft_ms: 200,
        p99_itl_ms: 13,
      },
      rejection_reasons: [],
      uncertainty: {
        cost_per_million_tokens: 0.1,
        p95_ttft_ms: 10,
        p99_itl_ms: 2,
      },
    },
    {
      configuration: {
        backend_candidate_id: "mock-fast",
        chunked_prefill: true,
        concurrency: 8,
        config_id: "cfg-predicted",
        max_batched_tokens: 2048,
        replicas: 3,
        routing_policy: "earliest_finish",
        warm_replicas: 2,
      },
      constraint_margins: { p95_ttft_ms: 80 },
      feasible: true,
      fidelity: "predicted",
      measured: null,
      predicted: {
        cost_per_million_tokens: 2.1,
        p95_ttft_ms: 170,
        p99_itl_ms: 9,
      },
      rejection_reasons: [],
      uncertainty: {
        cost_per_million_tokens: 0.2,
        p95_ttft_ms: 14,
        p99_itl_ms: 2,
      },
    },
  ],
  plan: {
    admission: {
      maximum_queue_time_ms: 200,
      queue_capacity: 256,
      reject_when_predicted_late: true,
    },
    api_version: "sloforge.dev/v1alpha1",
    autoscaling: {
      mode: "predictive",
      safety_margin: 0.15,
      target_utilization: 0.72,
    },
    batching: {
      dynamic_batching: true,
      maximum_active_sequences: 4,
      maximum_batch_delay_ms: 2,
      maximum_batched_tokens: 512,
    },
    engine: {
      dtype: "float32",
      maximum_active_sequences: 4,
      maximum_batched_tokens: 512,
      quantization: "none",
      runtime: "mock",
      tensor_parallelism: 1,
      version: "1.0.0",
    },
    hardware: {
      cpu: { architecture: "arm64", logical_cores: 8, model: "Test CPU" },
      gpu_count: 0,
      gpus: [],
      hourly_price_usd: 1.1,
      region: "local",
      system_memory_bytes: 16_000_000_000,
    },
    kind: "DeploymentPlan",
    metadata: {
      created_at: "2026-01-01T00:00:00Z",
      generation: 1,
      name: "sloforge-test-plan",
      uid: "plan-fixture-1",
    },
    model: {
      maximum_sequence_length: 32768,
      minimum_precision: "float32",
      model_id: "sloforge/test-model",
      revision: "test-v1",
    },
    predicted_metrics: {
      cost_per_million_tokens: {
        confidence: 0.95,
        lower: 1.3,
        measurement_ids: ["measurement-1"],
        point: 1.4,
        sample_count: 20,
        unit: "USD/million_tokens",
        upper: 1.5,
      },
      goodput_tokens_s: {
        confidence: 0.95,
        lower: 95,
        measurement_ids: ["measurement-1"],
        point: 100,
        sample_count: 20,
        unit: "tokens/s",
        upper: 105,
      },
      p95_ttft_ms: {
        confidence: 0.95,
        lower: 180,
        measurement_ids: ["measurement-1"],
        point: 200,
        sample_count: 20,
        unit: "ms",
        upper: 220,
      },
      p99_itl_ms: {
        confidence: 0.95,
        lower: 10,
        measurement_ids: ["measurement-1"],
        point: 13,
        sample_count: 20,
        unit: "ms",
        upper: 16,
      },
    },
    provenance: { optimizer_run_id: "optimizer-fixture" },
    replica_topology: {
      initial_replicas: 2,
      maximum_replicas: 4,
      minimum_replicas: 1,
      regions: ["local"],
    },
    routing: {
      kind: "slo_slack",
      targets: [{ variant: "mock-balanced", weight: 1 }],
    },
    schema_version: "1.0.0",
    slo: {
      inter_token_latency: [{ maximum_ms: 45, percentile: 99 }],
      minimum_availability: 0.99,
      objective_weights: { cost: 1, latency: 0.25 },
      ttft: [{ maximum_ms: 250, percentile: 95 }],
    },
    workload: {
      duration_seconds: 2,
      output_tokens: {
        empirical: [
          { value: 32, weight: 0.6 },
          { value: 128, weight: 0.4 },
        ],
        fixed_value: null,
        kind: "empirical",
        maximum: 128,
        minimum: 32,
      },
      prompt_tokens: {
        empirical: [
          { value: 64, weight: 0.5 },
          { value: 1024, weight: 0.5 },
        ],
        fixed_value: null,
        kind: "empirical",
        maximum: 1024,
        minimum: 64,
      },
      request_classes: [
        { deadline_ms: 1800, name: "interactive", priority: "interactive", weight: 0.7 },
        { deadline_ms: 6500, name: "long-context", priority: "batch", weight: 0.3 },
      ],
      seed: 7,
      trace_digest: { algorithm: "sha256", value: "fixture-digest" },
    },
  },
} as const;
