"""Absolute trust-boundary limits for Genesis policy documents."""

MAX_POLICY_DOCUMENT_BYTES = 1024 * 1024
MAX_POLICY_INSTRUCTIONS = 4096
MAX_POLICY_VARIABLES = 128
MAX_POLICY_NAME_BYTES = 128
MAX_POLICY_INTEGER_ABS = (1 << 63) - 1
MAX_POLICY_FLOAT_ABS = float(MAX_POLICY_INTEGER_ABS)
